---
# File to sen src files to Pi
# You need to copy your ssh keys to the pi in order for this to work
# ansible-playbook -i inventories/hosts -u pi deploy.yml
- hosts: pis
  become: yes
  gather_facts: false

  tasks:
     - name: copy src to /home/pi/
       copy:
           src: ../../src
           dest: /home/pi
           owner: pi
           group: pi
           mode: 0770

  post_tasks:
      - name: reboot PIs
        reboot:
